### ISSUE TITLE
App still uses old day color endpoint

### ISSUE THREAD

**Issue by kailan** [Syosset/syosset#84]
@rlefkowitz Can you update your app to fetch the day color from `https://syosseths.com/day` instead of `https://syosseths.com/day_color`?

If you can update the issue when done so we can remove the old endpoint that'd be great 👍

**Comment by rlefkowitz** [comment]
I can get the update submitted by Monday, although I have to remove notifications temporarily due to some logistical issues with the developer account.

**Comment by neiljohari** [comment]
Quick note: as of 91dd8fbb2fd76015f4f326590b46c865bd3ed2a1 the `/day` API is following a different format (legacy route remains unaffected). I've already informed @jweiss045, but it might be nice to have it documented here.

If I were you guys, instead of just ripping through the api output, I would implement a [jsonapi deserializer](http://jsonapi.org/implementations/).
You can use [our serializers](https://github.com/Syosset/syosset/tree/master/app/serializable_resources) as a reference for what data to extract.


Examples of what the [new API ](https://syosseths.com/day.json) returns:
No School:
```{"data":{"id":"current_day_color","type":"days","attributes":{"color":"No Color"},"relationships":{"closure":{"data":null}}},"jsonapi":{"version":"1.0"}}```

Red Day:
```{"data":{"id":"current_day_color","type":"days","attributes":{"color":"Red Day"},"relationships":{"closure":{"data":null}}},"jsonapi":{"version":"1.0"}}```

White Day:
```{"data":{"id":"current_day_color","type":"days","attributes":{"color":"White Day"},"relationships":{"closure":{"data":null}}},"jsonapi":{"version":"1.0"}}```

Active Closure:
```{"data":{"id":"current_day_color","type":"days","attributes":{"color":"No Color"},"relationships":{"closure":{"data":{"type":"closures","id":"5a4ec95f366a3530e7f41865"}}}},"included":[{"id":"5a4ec95f366a3530e7f41865","type":"closures","attributes":{"type":"snow","content":"This is due to the road and weather conditions. All activities will be cancelled including SCOPE.","start_date":"2018-01-03","end_date":"2018-01-04"}}],"jsonapi":{"version":"1.0"}}```

**Comment by jweiss045** [comment]
I have successfully implemented the changes and pushed out the update for the Android version of the app.

**Comment by jweiss045** [comment]
I have updated the Android version of the app with the new API.

**Comment by neiljohari** [comment]
@rlefkowitz @jweiss045 Are we good to remove the outdated endpoint now?

**Comment by rlefkowitz** [comment]
Yes, you can remove the endpoint now. 


On Sunday, January 14, 2018, 4:06 PM, Neil Johari <notifications@github.com> wrote:


@rlefkowitz @jweiss045 Are we good to remove the outdated endpoint now?
